@startuml
hide footbox

skinparam backgroundColor white

skinparam ActorStyle stickman
skinparam ActorBackgroundColor white
skinparam ActorBorderColor black
skinparam ActorFontColor black

skinparam ParticipantBackgroundColor white
skinparam ParticipantBorderColor black
skinparam ParticipantFontColor black

skinparam SequenceLifeLineBackgroundColor white
skinparam SequenceLifeLineBorderColor black

skinparam ArrowColor black
skinparam ArrowFontColor black

skinparam GroupBorderColor black
skinparam GroupBackgroundColor white
skinparam GroupHeaderFontColor black
skinparam GroupBodyBackgroundColor white

actor "Receptionist" as R
participant ": System" as S

R -> S : gemGæsteliste
activate S
S --> R : success
deactivate S

@enduml